# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: xbwee's blogs
subtitle: '思绪如风，偶尔在此停留'
description: '技术博客，杂记，随笔'
keywords:
author: xbwee
avatar:
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: https://www.xbwee.space
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  - type: git
    repository: https://github.com/xbwee1024/xbwee1024.github.io.git
    branch: master
    message: add/modify/delete posts
  - type: leancloud_counter_security_sync

# hexo-symbols-count-time
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
  exclude_codeblock: false
  awl: 4
  wpm: 275
  suffix: "mins."

filter_optimize:
  enable: true
  # remove the surrounding comments in each of the bundled files
  remove_comments: false
  css:
    # minify all css files
    minify: true
    # bundle loaded css files into one
    bundle: true
    # use a script block to load css elements dynamically
    delivery: true
    # make specific css content inline into the html page
    #   - only support the full path
    #   - default is ['css/main.css']
    inlines:
    excludes:
  js:
    # minify all js files
    minify: true
    # bundle loaded js files into one
    bundle: true
    excludes:
  # set the priority of this plugin,
  # lower means it will be executed first, default of Hexo is 10
  priority: 12

leancloud_counter_security:
  enable_sync: true
  app_id: 4GgdYKJV5fgexya6xmgU7OyD-gzGzoHsz
  app_key: 4UK5s8XhJdCYQ9gy48gp9CJf
  server_url: https://4ggdykjv.lc-cn-n1-shared.com
  username: xbwee
  password: "123456"






theme_config:
  # ---------------------------------------------------------------
  # Site Information Settings
  # See: https://theme-next.org/docs/getting-started/
  # ---------------------------------------------------------------

  favicon:
    small: /images/favicon-16x16-next.png
    medium: /images/favicon-32x32-next.png
    apple_touch_icon: /images/apple-touch-icon-next.png
    safari_pinned_tab: /images/logo.svg
    #android_manifest: /images/manifest.json
    #ms_browserconfig: /images/browserconfig.xml

  # Show multilingual switcher in footer.
  language_switcher: false

  footer:
    # Specify the date when the site was setup. If not defined, current year will be used.
    #since: 2015

    # Icon between year and copyright info.
    icon:
      # Icon name in Font Awesome. See: https://fontawesome.com/icons
      name: fa fa-heart
      # If you want to animate the icon, set it to true.
      animated: true
      # Change the color of icon, using Hex Code.
      color: "#ff0000"

    # If not defined, `author` from Hexo `_config.yml` will be used.
    copyright:

    # Powered by Hexo & NexT
    powered: true

    # Beian ICP and gongan information for Chinese users. See: https://beian.miit.gov.cn, http://www.beian.gov.cn
    beian:
      enable: false
      icp:
      # The digit in the num of gongan beian.
      gongan_id:
      # The full num of gongan beian.
      gongan_num:
      # The icon for gongan beian. See: http://www.beian.gov.cn/portal/download
      gongan_icon_url:

  # Creative Commons 4.0 International License.
  # See: https://creativecommons.org/share-your-work/licensing-types-examples
  # Available values of license: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
  # You can set a language value if you prefer a translated version of CC license, e.g. deed.zh
  # CC licenses are available in 39 languages, you can find the specific and correct abbreviation you need on https://creativecommons.org
  creative_commons:
    license: by-nc-sa
    sidebar: true
    post: true
    language:


  # ---------------------------------------------------------------
  # Scheme Settings
  # ---------------------------------------------------------------

  # Schemes
  # scheme: Muse
  #scheme: Mist
  scheme: Pisces
  #scheme: Gemini

  # Dark Mode
  darkmode: false


  # ---------------------------------------------------------------
  # Menu Settings
  # ---------------------------------------------------------------

  # Usage: `Key: /link/ || icon`
  # Key is the name of menu item. If the translation for this item is available, the translated text will be loaded, otherwise the Key name will be used. Key is case-senstive.
  # Value before `||` delimiter is the target link, value after `||` delimiter is the name of Font Awesome icon.
  # When running the site in a subdirectory (e.g. yoursite.com/blog), remove the leading slash from link value (/archives -> archives).
  # External url should start with http:// or https://
  menu:
    home: / || fa fa-home
    about: /about/ || fa fa-user
    tags: /tags/ || fa fa-tags
    categories: /categories/ || fa fa-th
    archives: /archives/ || fa fa-archive
    #schedule: /schedule/ || fa fa-calendar
    #sitemap: /sitemap.xml || fa fa-sitemap
    #commonweal: /404/ || fa fa-heartbeat
    hot: /hot/ || fa fa-signal

  # Enable / Disable menu icons / item badges.
  menu_settings:
    icons: true
    badges: true

  




  # ---------------------------------------------------------------
  # Sidebar Settings
  # See: https://theme-next.org/docs/theme-settings/sidebar
  # ---------------------------------------------------------------

  sidebar:
    # Sidebar Position.
    position: left
    #position: right

    # Manual define the sidebar width. If commented, will be default for:
    # Muse | Mist: 320
    # Pisces | Gemini: 240
    #width: 300

    # Sidebar Display (only for Muse | Mist), available values:
    #  - post    expand on posts automatically. Default.
    #  - always  expand for all pages automatically.
    #  - hide    expand only when click on the sidebar toggle icon.
    #  - remove  totally remove sidebar including sidebar toggle.
    display: post

    # Sidebar padding in pixels.
    padding: 18
    # Sidebar offset from top menubar in pixels (only for Pisces | Gemini).
    offset: 12
    # Enable sidebar on narrow view (only for Muse | Mist).
    onmobile: false

  # Sidebar Avatar
  avatar:
    # Replace the default image and set the url here.
    url: https://s.gravatar.com/avatar/72c684138f4483ba31279fe9c5be952c?s=80 #/images/avatar.gif
    # If true, the avatar will be dispalyed in circle.
    rounded: true
    # If true, the avatar will be rotated with the cursor.
    rotated: false

  # Posts / Categories / Tags in sidebar.
  site_state: true

  # Social Links
  # Usage: `Key: permalink || icon`
  # Key is the link label showing to end users.
  # Value before `||` delimiter is the target permalink, value after `||` delimiter is the name of Font Awesome icon.
  social:
    GitHub: https://github.com/xbwee1024 || fab fa-github
    E-Mail: mailto:xiaobin.wee@gmail.com || fa fa-envelope
    #Weibo: https://weibo.com/yourname || fab fa-weibo
    #Google: https://plus.google.com/yourname || fab fa-google
    #Twitter: https://twitter.com/yourname || fab fa-twitter
    #FB Page: https://www.facebook.com/yourname || fab fa-facebook
    #StackOverflow: https://stackoverflow.com/yourname || fab fa-stack-overflow
    #YouTube: https://youtube.com/yourname || fab fa-youtube
    #Instagram: https://instagram.com/yourname || fab fa-instagram
    #Skype: skype:yourname?call|chat || fab fa-skype

  social_icons:
    enable: true
    icons_only: false
    transition: false

  # Blog rolls
  links_settings:
    icon: fa fa-link
    title: Links
    # Available values: block | inline
    layout: block

  links:
    #Title: http://yoursite.com




  # ---------------------------------------------------------------
  # Statistics and Analytics
  # See: https://theme-next.org/docs/third-party-services/statistics-and-analytics
  # ---------------------------------------------------------------

  # Show number of visitors of each article.
  # You can visit https://leancloud.cn to get AppID and AppKey.
  # AppID and AppKey are recommended to be the same as valine's for counter compatibility.
  # Do not enable both `valine.visitor` and `leancloud_visitors`.
  leancloud_visitors:
    enable: false
    app_id: 4GgdYKJV5fgexya6xmgU7OyD-gzGzoHsz
    app_key: 4UK5s8XhJdCYQ9gy48gp9CJf
    # Required for apps from CN region
    server_url: https://4ggdykjv.lc-cn-n1-shared.com
    # Dependencies: https://github.com/theme-next/hexo-leancloud-counter-security
    # If you don't care about security in leancloud counter and just want to use it directly
    # (without hexo-leancloud-counter-security plugin), set `security` to `false`.
    security: true

    # Valine
    # valine: //cdn.jsdelivr.net/npm/valine@1/dist/Valine.min.js
    # valine: //cdnjs.cloudflare.com/ajax/libs/valine/1.3.10/Valine.min.js
    valine: https://cdn.jsdelivr.net/npm/valine@1.4.14/dist/Valine.min.js



  # ---------------------------------------------------------------
  # Comments Settings
  # See: https://theme-next.org/docs/third-party-services/comments
  # ---------------------------------------------------------------

  # Multiple Comment System Support
  comments:
    # Available values: tabs | buttons
    style: tabs
    # Choose a comment system to be displayed by default.
    # Available values: changyan | disqus | disqusjs | gitalk | livere | valine
    active:
    # Setting `true` means remembering the comment system selected by the visitor.
    storage: true
    # Lazyload all comment systems.
    lazyload: false
    # Modify texts or order for any navs, here are some examples.
    nav:
      #disqus:
      #  text: Load Disqus
      #  order: -1
      #gitalk:
      #  order: -2

  # Disqus
  disqus:
    enable: false
    shortname:
    count: true
    #post_meta_order: 0

  # DisqusJS
  # Alternative Disqus - Render comment component using Disqus API.
  # Demo: https://suka.js.org/DisqusJS/
  # For more information: https://github.com/SukkaW/DisqusJS
  disqusjs:
    enable: false
    # API Endpoint of Disqus API (https://disqus.com/api/).
    # Leave api empty if you are able to connect to Disqus API. Otherwise you need a reverse proxy for it.
    # For example:
    # api: https://disqus.skk.moe/disqus/
    api:
    apikey: # Register new application from https://disqus.com/api/applications/
    shortname: # See: https://disqus.com/admin/settings/general/

  # Valine
  # For more information: https://valine.js.org, https://github.com/xCss/Valine
  valine:
    enable: true
    appid: 4GgdYKJV5fgexya6xmgU7OyD-gzGzoHsz
    appkey: 4UK5s8XhJdCYQ9gy48gp9CJf
    notify: false # Mail notifier
    verify: false # Verification code
    placeholder: 秒注册发评论 # Comment box placeholder
    avatar: mm # Gravatar style
    guest_info: nick,mail,link # Custom comment header
    pageSize: 10 # Pagination size
    language: zh-CN
    visitor: true # Article reading statistic
    comment_count: true # If false, comment count will only be displayed in post page, not in home page
    recordIP: false # Whether to record the commenter IP
    serverURLs: # When the custom domain name is enabled, fill it in here (it will be detected automatically by default, no need to fill in)
    #post_meta_order: 0
